monitor=,highres,auto,1

source = ~/.config/hypr/hyprland/env.conf
source = ~/.config/hypr/hyprland/execs.conf
source = ~/.config/hypr/hyprland/variables.conf
source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/rules.conf
source = ~/.config/hypr/hyprland/colors.conf
source = ~/.config/hypr/hyprland/keybinds.conf

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
}