exec-once = waybar
exec-once = swww-daemon
exec-once = swww img /home/deadspy/Downloads/7.png --transition-type outer --transition-pos 0.85,0.85 --transition-step 90
exec-once = nm-applet --indicator
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dunst