windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:title ^(Open File)$, float on
windowrule = match:title ^(Select a File)$, float on
windowrule = match:title ^(Choose wallpaper)$, float on
windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, pin on
windowrule = match:class ^(kitty)$, opacity 0.85 0.85 on
layerrule = animation fade, match:namespace logout_dialog
layerrule = blur true, match:namespace logout_dialog
layerrule = blur true, match:namespace launcher