# Terminal
$terminal = kitty

# File Manager
$fileManager = thunar

# Browser
$browser = google-chrome-stable

# Editors
$codeEditor = code
$textEditor = mousepad

# Utilities
$volumeMixer = pavucontrol
$taskManager = kitty -e btop

# Configuration logic
$dontLoadDefaultExecs =
$dontLoadDefaultGeneral =
$dontLoadDefaultRules =
$dontLoadDefaultKeybinds =